### ISSUE TITLE
@link-shell-extension: Version update to 3.9.2.7

### ISSUE THREAD

**Issue by richardmalone** [minorgod/scoop-minorgod#1]
Hi, thanks for the bucket.

LinkShellExtension has been updated to version 3.9.2.7 on 15 Oct. Would it be possible to update the .json?

Thanks, Richard

**Comment by minorgod** [comment]
Glad you found my bucket useful.  Actually, looking at that json config now, it looks like I should probably improve it with some auto-update functionality anyway, so I'll do that and push a new version in the next few hours.

**Comment by minorgod** [comment]
Sorry, I forgot to close this issue after I updated the manifest. Updated it again today to version 3.931.
